version: '3.8'
services:
  backend:
    image: ultimate-sports-betting-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "./backend/main.py"]
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    restart: always
  frontend:
    image: ultimate-sports-betting-frontend:latest
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    command: ["npm", "run", "preview"]
    ports:
      - "80:5173"
    env_file:
      - .env.example
    restart: always
