import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import ThemeToggle from './ThemeToggle';
import { BellIcon, UserCircleIcon } from '@heroicons/react/24/outline';
import { Link } from 'react-router-dom';
import { Menu, Transition } from '@headlessui/react';
import { useAuth } from '../providers/useAuth';
export default function Navbar() {
    const { user, logout } = useAuth();
    return (_jsx("nav", { className: "bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700", children: _jsx("div", { className: "mx-auto max-w-7xl px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex h-16 justify-between", children: [_jsx("div", { className: "flex", children: _jsx("div", { className: "flex flex-shrink-0 items-center", children: _jsx(Link, { to: "/", children: _jsx("img", { alt: "BetPro AI", className: "h-8 w-auto", src: "/logo.svg" }) }) }) }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx(ThemeToggle, {}), _jsxs("button", { className: "rounded-full bg-white dark:bg-gray-800 p-1 text-gray-400 hover:text-gray-500 dark:hover:text-gray-300", type: "button", children: [_jsx("span", { className: "sr-only", children: "View notifications" }), _jsx(BellIcon, { "aria-hidden": "true", className: "h-6 w-6" })] }), _jsxs(Menu, { as: "div", className: "relative ml-3", children: [_jsxs(Menu.Button, { className: "flex rounded-full bg-white dark:bg-gray-800 text-sm focus:outline-none", children: [_jsx("span", { className: "sr-only", children: "Open user menu" }), _jsx(UserCircleIcon, { "aria-hidden": "true", className: "h-8 w-8 text-gray-400" })] }), _jsx(Transition, { enter: "transition ease-out duration-200", enterFrom: "transform opacity-0 scale-95", enterTo: "transform opacity-100 scale-100", leave: "transition ease-in duration-75", leaveFrom: "transform opacity-100 scale-100", leaveTo: "transform opacity-0 scale-95", children: _jsxs(Menu.Items, { className: "absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white dark:bg-gray-800 py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none", children: [_jsx(Menu.Item, { children: ({ active }) => (_jsx(Link, { className: `${active ? 'bg-gray-100 dark:bg-gray-700' : ''} block px-4 py-2 text-sm text-gray-700 dark:text-gray-200`, to: "/settings", children: "Settings" })) }), _jsx(Menu.Item, { children: ({ active }) => (_jsx("button", { className: `${active ? 'bg-gray-100 dark:bg-gray-700' : ''} block w-full text-left px-4 py-2 text-sm text-gray-700 dark:text-gray-200`, onClick: logout, children: "Sign out" })) })] }) })] })] })] }) }) }));
}
