name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint ./frontend --max-warnings=0

    - name: Run TypeScript type check
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test

    - name: Build frontend
      run: npm run build --workspace=frontend
